# Generated by Django 2.0.5 on 2020-05-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
