# Generated by Django 2.0.5 on 2020-05-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200511_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
